# Generated by Django 3.1.5 on 2021-01-10 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=250)),
                ('editor', models.CharField(max_length=250)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('schedule_time', models.DateTimeField(default=datetime.datetime.now)),
                ('post_content', models.TextField()),
                ('post_title', models.CharField(max_length=1000)),
                ('post_status', models.CharField(max_length=100)),
                ('post_modified', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.TextField()),
                ('feature_image_url', models.ImageField(upload_to='')),
            ],
        ),
    ]
