# Generated by Django 3.1.5 on 2021-01-11 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('schedule_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_content', models.TextField()),
                ('post_title', models.CharField(max_length=1000)),
                ('post_status', models.CharField(max_length=100)),
                ('post_modified', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(max_length=500)),
                ('keywords', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_description', models.TextField()),
                ('feature_image_url', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
