# Generated by Django 3.2.8 on 2021-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_static',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
