# Generated by Django 3.1.5 on 2021-08-28 20:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='newssource',
            name='image',
            field=models.ImageField(default='/media/blog/default.png', max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_image_url',
            field=models.ImageField(default='/media/blog/default.png', max_length=1000, upload_to=''),
        ),
    ]
