# Generated by Django 3.1.5 on 2021-08-28 21:10

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210828_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPost',
        ),
        migrations.AlterField(
            model_name='newssource',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=django_quill.fields.QuillField(),
        ),
    ]
