# Generated by Django 3.1.5 on 2021-08-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210828_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressreleaseform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pressreleaseform',
            name='discount_description',
        ),
    ]
