# Generated by Django 3.1.5 on 2021-09-12 12:31

import blog.models
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210829_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssource',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_date',)},
        ),
        migrations.AddField(
            model_name='pressreleaseform',
            name='description',
            field=django_quill.fields.QuillField(default=''),
        ),
        migrations.AddField(
            model_name='pressreleaseform',
            name='discount_description',
            field=django_quill.fields.QuillField(default=''),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='description',
            field=django_quill.fields.QuillField(default=''),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='image',
            field=models.ImageField(default='blog/source/default.png', upload_to=blog.models.ns_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_image_url',
            field=models.ImageField(default='blog/post/default.jpg', upload_to=blog.models.post_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=django_quill.fields.QuillField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='seen',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
