# Generated by Django 3.1.5 on 2021-09-12 12:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210912_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressreleaseform',
            name='image',
            field=models.ImageField(upload_to=blog.models.press_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pressreleaseform',
            name='logo',
            field=models.ImageField(upload_to=blog.models.logo_upload_to, verbose_name='logo'),
        ),
    ]
