# Generated by Django 3.1.5 on 2021-09-24 10:06

from django.db import migrations
import django_quill.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210912_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='pressreleaseform',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='pressreleaseform',
            name='discount_description',
            field=django_quill.fields.QuillField(),
        ),
    ]
