# Generated by Django 3.1.5 on 2021-09-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210924_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pressreleaseform',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pressreleaseform',
            name='discount_description',
            field=models.TextField(),
        ),
    ]
