# Generated by Django 3.1.5 on 2021-09-24 14:30

import blog.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210924_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator])),
                ('image', models.ImageField(default='blog/press/default.jpg', upload_to=blog.models.press_upload_to, verbose_name='Image')),
                ('heading', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WriteForUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator])),
                ('image', models.ImageField(default='blog/write4us/default.jpg', upload_to=blog.models.wfu_upload_to, verbose_name='Image')),
                ('heading', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PressReleaseForm',
        ),
    ]
